# Generated by Django 5.2.9 on 2025-12-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechargerequest',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rechargerequest',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rechargerequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('SCHEDULED', 'Scheduled')], default='PENDING', max_length=20),
        ),
    ]
