# Generated by Django 5.2.9 on 2025-12-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0002_rechargerequest_is_scheduled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechargerequest',
            name='category',
            field=models.CharField(choices=[('MOBILE_PREPAID', 'Mobile Prepaid'), ('MOBILE_POSTPAID', 'Mobile Postpaid'), ('DTH', 'DTH'), ('BROADBAND', 'Broadband'), ('ELECTRICITY', 'Electricity'), ('GAS', 'Gas'), ('WATER', 'Water'), ('OTHER', 'Other')], default='MOBILE_PREPAID', max_length=20),
        ),
        migrations.AlterField(
            model_name='rechargerequest',
            name='mobile_number',
            field=models.CharField(max_length=30),
        ),
    ]
