# Generated by Django 5.2.9 on 2025-12-31 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0003_rechargerequest_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('MOBILE_PREPAID', 'Mobile Prepaid'), ('MOBILE_POSTPAID', 'Mobile Postpaid'), ('DTH', 'DTH'), ('BROADBAND', 'Broadband'), ('ELECTRICITY', 'Electricity'), ('GAS', 'Gas'), ('WATER', 'Water'), ('OTHER', 'Other')], max_length=20)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
    ]
