# Generated by Django 5.2.9 on 2026-01-03 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0004_operator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.CharField(blank=True, max_length=100, null=True)),
                ('validity', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_benefits', models.TextField(blank=True, null=True)),
                ('plan_type', models.CharField(choices=[('TOPUP', 'Topup'), ('DATA', 'Data'), ('SMS', 'SMS'), ('UNLIMITED', 'Unlimited'), ('ROAMING', 'Roaming'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('circle', models.CharField(default='ALL', max_length=100)),
                ('talktime', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='recharge.operator')),
            ],
        ),
    ]
