# Generated by Django 5.2.9 on 2026-01-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0005_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='data',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='talktime',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='validity',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
