# Generated by Django 5.2.9 on 2026-01-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0006_alter_plan_data_alter_plan_talktime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechargerequest',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rechargerequest',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
