# Generated by Django 5.2.9 on 2026-01-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0007_rechargerequest_platform_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
