# Generated by Django 5.2.9 on 2026-01-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0008_operator_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechargerequest',
            name='costumer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
