# Generated by Django 5.2.9 on 2025-12-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_address_user_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_user_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
