# Generated by Django 5.2.9 on 2025-12-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topuprequest',
            name='screenshot',
        ),
        migrations.AddField(
            model_name='topuprequest',
            name='transaction_reference',
            field=models.CharField(default='0000', help_text='Last 4 digits of Transaction ID', max_length=4),
        ),
    ]
