# Generated by Django 5.2.9 on 2026-01-03 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0008_operator_logo_url'),
        ('wallet', '0004_transaction_operator_logo_transaction_operator_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='recharge_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='recharge.rechargerequest'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='topup_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='wallet.topuprequest'),
        ),
    ]
