# Generated by Django 5.2.9 on 2026-01-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_transaction_recharge_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='target_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
