# Generated by Django 5.2.9 on 2026-01-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_transaction_target_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='target_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
