# Generated by Django 5.2.9 on 2026-01-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(max_length=50)),
                ('version_code', models.IntegerField(unique=True)),
                ('apk_file', models.FileField(upload_to='apks/')),
                ('release_notes', models.TextField(blank=True, null=True)),
                ('is_force_update', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-version_code'],
            },
        ),
    ]
